# Form implementation generated from reading ui file 'c:\Users\Hanzala\Downloads\DBMS Project\DB Project\1_Dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 828)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self._1_tableWidge_SquadData = QtWidgets.QTableWidget(parent=self.centralwidget)
        self._1_tableWidge_SquadData.setGeometry(QtCore.QRect(10, 40, 1001, 401))
        self._1_tableWidge_SquadData.setObjectName("_1_tableWidge_SquadData")
        self._1_tableWidge_SquadData.setColumnCount(5)
        self._1_tableWidge_SquadData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self._1_tableWidge_SquadData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self._1_tableWidge_SquadData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self._1_tableWidge_SquadData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self._1_tableWidge_SquadData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self._1_tableWidge_SquadData.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 10, 55, 16))
        self.label.setObjectName("label")
        self._1_pushButton_PlayerContracts = QtWidgets.QPushButton(parent=self.centralwidget)
        self._1_pushButton_PlayerContracts.setGeometry(QtCore.QRect(70, 530, 191, 111))
        self._1_pushButton_PlayerContracts.setObjectName("_1_pushButton_PlayerContracts")
        self._1_pushButton_UpcominMatches = QtWidgets.QPushButton(parent=self.centralwidget)
        self._1_pushButton_UpcominMatches.setGeometry(QtCore.QRect(420, 530, 181, 111))
        self._1_pushButton_UpcominMatches.setObjectName("_1_pushButton_UpcominMatches")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(750, 530, 171, 111))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 26))
        self.menubar.setObjectName("menubar")
        self.menuTeam_Management_Page = QtWidgets.QMenu(parent=self.menubar)
        self.menuTeam_Management_Page.setObjectName("menuTeam_Management_Page")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTeam_Management_Page.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self._1_tableWidge_SquadData.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Player Name"))
        item = self._1_tableWidge_SquadData.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Team"))
        item = self._1_tableWidge_SquadData.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Position"))
        item = self._1_tableWidge_SquadData.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Goals"))
        item = self._1_tableWidge_SquadData.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Assists"))
        self.label.setText(_translate("MainWindow", "Squad"))
        self._1_pushButton_PlayerContracts.setText(_translate("MainWindow", "Player Contracts"))
        self._1_pushButton_UpcominMatches.setText(_translate("MainWindow", "Upcoming Matches"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.menuTeam_Management_Page.setTitle(_translate("MainWindow", "Team Management Page"))
