# Form implementation generated from reading ui file 'c:\Users\Hanzala\Downloads\DBMS Project\DB Project\3_WinProbability.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 798)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self._3_label_WinProbability = QtWidgets.QLabel(parent=self.centralwidget)
        self._3_label_WinProbability.setGeometry(QtCore.QRect(30, 490, 111, 16))
        self._3_label_WinProbability.setObjectName("_3_label_WinProbability")
        self._3_progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self._3_progressBar.setGeometry(QtCore.QRect(220, 490, 561, 23))
        self._3_progressBar.setProperty("value", 24)
        self._3_progressBar.setObjectName("_3_progressBar")
        self._3_pushButton_CalculateWinProbability = QtWidgets.QPushButton(parent=self.centralwidget)
        self._3_pushButton_CalculateWinProbability.setGeometry(QtCore.QRect(380, 350, 181, 28))
        self._3_pushButton_CalculateWinProbability.setObjectName("_3_pushButton_CalculateWinProbability")
        self._3_tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self._3_tableWidget.setGeometry(QtCore.QRect(20, 90, 981, 161))
        self._3_tableWidget.setObjectName("_3_tableWidget")
        self._3_tableWidget.setColumnCount(5)
        self._3_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self._3_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self._3_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self._3_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self._3_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self._3_tableWidget.setHorizontalHeaderItem(4, item)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 30, 271, 51))
        self.label_2.setObjectName("label_2")
        self._3_label_MatchidInput = QtWidgets.QLabel(parent=self.centralwidget)
        self._3_label_MatchidInput.setGeometry(QtCore.QRect(30, 290, 101, 16))
        self._3_label_MatchidInput.setObjectName("_3_label_MatchidInput")
        self._3_lineEdit_MatchidInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self._3_lineEdit_MatchidInput.setGeometry(QtCore.QRect(150, 290, 131, 22))
        self._3_lineEdit_MatchidInput.setObjectName("_3_lineEdit_MatchidInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 26))
        self.menubar.setObjectName("menubar")
        self.menuWin_Probability_Prediction = QtWidgets.QMenu(parent=self.menubar)
        self.menuWin_Probability_Prediction.setObjectName("menuWin_Probability_Prediction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuWin_Probability_Prediction.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self._3_label_WinProbability.setText(_translate("MainWindow", "Win Probablility"))
        self._3_pushButton_CalculateWinProbability.setText(_translate("MainWindow", "Calculate Win Probability"))
        item = self._3_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Match_id"))
        item = self._3_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Home Team"))
        item = self._3_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Away Team"))
        item = self._3_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Venue"))
        item = self._3_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        self.label_2.setText(_translate("MainWindow", "Upcoming Matches"))
        self._3_label_MatchidInput.setText(_translate("MainWindow", "Match_Id Input"))
        self.menuWin_Probability_Prediction.setTitle(_translate("MainWindow", "Win Probability Prediction"))
